((haskell-mode . ((haskell-indent-spaces . 4)
                  (haskell-process-use-ghci . t)
                  (hindent-style . "gibiansky")))
 (hamlet-mode . ((hamlet/basic-offset . 4)
                 (haskell-process-use-ghci . t))))
